services:
  laravel:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: emk_laravel_local
    pull_policy: build
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - emk_net

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - laravel
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - emk_net

  django:
    build:
      context: ../emk-reports
      dockerfile: Dockerfile
    image: emk_django_local
    pull_policy: build
    env_file: !override
      - ../emk-reports/.env
    command: python manage.py runserver 0.0.0.0:8084
    ports:
      - "8084:8084"
    volumes:
      - ../emk-reports:/app
    networks:
      - emk_net

  spring:
    image: maven:3.9-eclipse-temurin-21
    env_file: !override
      - ../financial-planing/.env
    working_dir: /app
    volumes:
      - ../financial-planing:/app
      - ~/.m2:/root/.m2
    entrypoint: []
    command: mvn spring-boot:run
    ports:
      - "8085:8085"
    environment:
      SERVER_PORT: 8085
    networks:
      - emk_net

  node:
    build:
      context: ../emk-sena-rsr-expenses-back
      dockerfile: Dockerfile
    image: emk_node_local
    pull_policy: build
    env_file:
      - ../emk-sena-rsr-expenses-back/.env
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ../emk-sena-rsr-expenses-back:/app
      - /app/node_modules
    command: npm start
    networks:
      - emk_net

  locust:
    image: locustio/locust:latest
    container_name: emk_locust
    depends_on:
      - nginx
    env_file:
      - .env
    environment:
      LOCUST_HOST: http://nginx
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py:ro
    command: -f /mnt/locust/locustfile.py --web-host=0.0.0.0
    networks:
      - emk_net

networks:
  emk_net:
    driver: bridge
